# -*- coding: utf-8 -*-
"""resumegithub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1whudTm0RAyj9av6tkJASW5nhGDXzQcld
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# ---------------- PAGE CONFIG ----------------
# I set the page layout to wide so the dashboard looks cleaner and easier to read
st.set_page_config(
    page_title="Income & Work Analysis Dashboard",
    layout="wide"
)

# ---------------- TITLE ----------------
# This is the main title of my dashboard
st.title("Income and Work Analysis Dashboard")

# I added this description to explain what the app is showing
st.markdown("""
This dashboard lets me explore how income and work patterns change based on telework status.
I built this to make the data easier to understand through interactive visualizations.
""")

# ---------------- LOAD DATA ----------------
# I load the dataset that I cleaned and analyzed in my project
df = pd.read_csv("IPUMS.csv")

# ---------------- DATA CLEANING ----------------
# I replace missing telework values with 0 (assuming no telework pay)
df['TELWRKPAY'] = df['TELWRKPAY'].fillna(0)

# I remove invalid income values based on dataset coding rules
df = df[df['INCWAGE'] < 99999999]

# I remove invalid work hour values
df = df[df['WKSWORK1'] > 0]
df = df[(df['UHRSWORKT'] > 0) & (df['UHRSWORKT'] < 997)]

# ---------------- FEATURE ENGINEERING ----------------
# I created a new variable to measure efficiency (income per work effort)
df['HourlyEfficiency'] = df['INCWAGE'] / (df['WKSWORK1'] * df['UHRSWORKT'])

# ---------------- SIDEBAR FILTER ----------------
# I added a filter so users can compare telework vs non-telework workers
st.sidebar.header("Filters")

telework_option = st.sidebar.selectbox(
    "Telework Pay",
    [0, 1],
    format_func=lambda x: "No Telework Pay" if x == 0 else "Receives Telework Pay"
)

# I filter the dataset based on user selection
df = df[df['TELWRKPAY'] == telework_option]

# ---------------- LAYOUT ----------------
st.subheader("Key Insights")

col1, col2 = st.columns(2)

# ---------------- PLOT 1 ----------------
with col1:
    st.markdown("### Income by Age")

    # I group the data to show average income by age
    income_age = df.groupby("AGE")["INCWAGE"].mean().reset_index()

    fig1 = px.line(
        income_age,
        x="AGE",
        y="INCWAGE",
        title="Average Income by Age"
    )

    st.plotly_chart(fig1, use_container_width=True)

# ---------------- PLOT 2 ----------------
with col2:
    st.markdown("### Hourly Efficiency Distribution")

    fig2 = px.histogram(
        df,
        x="HourlyEfficiency",
        nbins=30,
        title="Distribution of Hourly Efficiency"
    )

    st.plotly_chart(fig2, use_container_width=True)

# ---------------- SUMMARY ----------------
# I added this section to show key statistics after filtering
with st.expander("View Summary Statistics"):
    st.write("Number of observations:", df.shape[0])
    st.write("Average income:", round(df["INCWAGE"].mean(), 2))
    st.write("Average hourly efficiency:", round(df["HourlyEfficiency"].mean(), 2))
