# -*- coding: utf-8 -*-
"""resumegithub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1whudTm0RAyj9av6tkJASW5nhGDXzQcld
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="Income & Work Analysis Dashboard",
    layout="wide"
)

# ---------------- TITLE ----------------
st.title("Income and Work Analysis Dashboard")

# ---------------- RECRUITER-FACING DESCRIPTION ----------------
st.markdown("""
### About This Project

I built this interactive dashboard to analyze how income and work behavior vary across individuals using real labor survey data.

The application allows users to explore:
- Income trends across different ages  
- Distribution of work efficiency  
- Differences between telework and non-telework employees  

This project demonstrates my ability to clean data, create new features, and build interactive data applications using Python and Streamlit.
""")

# ---------------- LOAD DATA ----------------
df = pd.read_csv("IPUMS.csv")

# ---------------- CLEAN DATA ----------------
df['TELWRKPAY'] = df['TELWRKPAY'].fillna(0)

df = df[df['INCWAGE'] < 99999999]
df = df[df['WKSWORK1'] > 0]
df = df[(df['UHRSWORKT'] > 0) & (df['UHRSWORKT'] < 997)]

# ---------------- FEATURE ENGINEERING ----------------
df['HourlyEfficiency'] = df['INCWAGE'] / (df['WKSWORK1'] * df['UHRSWORKT'])

# ---------------- SIDEBAR FILTER ----------------
st.sidebar.header("Filters")

telework_option = st.sidebar.selectbox(
    "Telework Pay",
    [0, 1],
    format_func=lambda x: "No Telework Pay" if x == 0 else "Receives Telework Pay"
)

df = df[df['TELWRKPAY'] == telework_option]

# ---------------- LAYOUT ----------------
st.subheader("Key Insights")

col1, col2 = st.columns(2)

# ---------------- PLOT 1 ----------------
with col1:
    st.markdown("### Income by Age")

    income_age = df.groupby("AGE")["INCWAGE"].mean().reset_index()

    fig1 = px.line(
        income_age,
        x="AGE",
        y="INCWAGE",
        title="Average Income by Age"
    )

    st.plotly_chart(fig1, use_container_width=True)

# ---------------- PLOT 2 ----------------
with col2:
    st.markdown("### Hourly Efficiency Distribution")

    fig2 = px.histogram(
        df,
        x="HourlyEfficiency",
        nbins=30,
        title="Distribution of Hourly Efficiency"
    )

    st.plotly_chart(fig2, use_container_width=True)

# ---------------- SUMMARY ----------------
with st.expander("View Summary Statistics"):
    st.write("Number of observations:", df.shape[0])
    st.write("Average income:", round(df["INCWAGE"].mean(), 2))
    st.write("Average hourly efficiency:", round(df["HourlyEfficiency"].mean(), 2))
